---
- name: Copying files from controller to hosts
  hosts: planetexpress
  connection: ssh
  gather_facts: true # default is true

  tasks:

    - name: Copy Fry's resume to hosts
      ansible.builtin.copy:
        src: ~/Cohort/Ansible/files/fry.txt   # on the controller
        dest: ~/fry.txt      # home directory on hosts

